# Site settings
title: Social Tables Engineering Code of Conduct
email: eng@socialtables.com
description: > # This code of conduct governs the environment of the Social Tables Engineering team.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://code-of-conduct.socialtables.com" # the base hostname & protocol for your site
twitter_username: socialtables
github_username:  socialtables

# Build settings
markdown: kramdown
